apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: true
    editable: true
    jsonData:
      defaultDatabase: raw
      port: 8123
      server: clickhouse
      username: clickhouse
      tlsSkipVerify: false
      protocol: http
    secureJsonData:
      password: clickhouse
